---
name: github
provider: github.com
repository: docker-dbxcli
url: https://github.com/cardboardci/docker-dbxcli
clone:
  ssh: git@github.com:cardboardci/docker-dbxcli.git
  https: https://github.com/cardboardci/docker-dbxcli.git